### ISSUE TITLE
README out of sync with 3.0

### ISSUE THREAD

**Issue by dloomb** [Rivukis/Spry#3]
The example in the README doesn't work with Swift 4.

I copied the example exactly and got the following errors:

`Type 'FakeStringService' does not conform to protocol 'Spyable'`

`Type 'FakeStringService.StaticFunction' does not conform to protocol 'StringRepresentable'`

`Type 'FakeStringService.Function' does not conform to protocol 'StringRepresentable'`

**Comment by Rivukis** [comment]
Looks like there were two issues described here.
1. Still using "StaticFunction" in the readme
2. A bug in the default implement for StringRepresentable. The default implementation was internal instead of public.

Both have been fixed in version 3.0.1

Thank you for bringing this to my attention!
