### ISSUE TITLE
Nimble 9

### ISSUE THREAD

**Issue by Servus7** [Rivukis/Spry#8]
Spry+Nimble dose not work with Nimble 9

**Comment by Rivukis** [comment]
Thank you for mentioning this issue! I'm unable to actively contribute to the code as that would transfer ownership to the company I work for. However, I've added a new contributor who is able to update this project. One main addition is getting this codebase up-to-date with Swift, Quick, Nimble, etc.

**Comment by paulhise1** [comment]
Spry+Nimble has now been moved into the main project and is compatible with Nimble 9.
